project:
  type: website
  output-dir: docs/
  render:
    - "*.qmd"   
  resources:
    - static/**     
    
website:
  search: false    
  sidebar:
    header: |
      <a href="./"><div style="margin-left:-50px;margin-top:-50px;">![](/static/logo.png){width=275}</div></a>
      <div style="margin-top:-40px;margin-bottom:-25px;">
      **TUC-PRME-26 | MA-S01**
      </div>
    collapse-level: 1
    style: floating
    contents:
      - section: "I: Vorbesprechung"
        contents:
          - href: S01_SteyerEid2001BoxFandG_01.qmd
            text: "A | Grundlage und Rechenregeln"
          - href: S01_SteyerEid2001Game_01.qmd
            text: "B | MatheQuest: SEM"
      - section: "II: Grundlagen"
        contents:
          - href: S02_EFA_01.qmd
            text: "Rückblick: Explorative Faktorenanalyse"
          - href: S02_Attenuation_01.qmd
            text: "A | Übung 1"
          - href: S02_PD_01.qmd
            text: "B | Übung 2"
          - href: S02_PD_02.qmd
            text: "C | Übung 3"
      - section: " III: Schätzung"
        contents:
          - href: S03_CFA_01.qmd
            text: "A | Live"
          - href: S03_CFA_02.qmd
            text: "B | Übung 1"
          - href: S03_CFA_03.qmd
            text: "C | Übung 2"     
          - href: S03_Estimation_01.qmd
            text: "D | `parTable()` und `lavTech()`"
          - href: S03_Estimation_02.qmd
            text: "E | Illustration von Modelltests"            
          - href: S03_Multigroup_01.qmd
            text: "F | Mehgruppenmodelle verstehen"
          - href: S03_rosseelTutorialUnderstandingSEM2025_Interactive_01.qmd
            text: "ℹ Tutorial von Rosseel & Vidal (2025) - 1"
          - href: S03_rosseelTutorialUnderstandingSEM2025_Interactive_02.qmd
            text: "ℹ Tutorial von Rosseel & Vidal (2025) - 2"               
      - section: "IV: Einbettung"
        contents:            
          - href: S04_OrdinalSEM_01.qmd
            text: "A | Live Ordinal SEM"        
          - href: S04_OrdinalIRT_01.qmd
            text: "B | Übung Ordinal vs. IRT"
          - href: S04_SimulationLavaan_01.qmd
            text: "C | Daten mit `lavaan` erzeugen"        
          - href: S04_SimulationLavaan_02.qmd
            text: "D | ℹ Strukturierung nach Wang & Rhemtulla (2021)"            
          - href: S04_rosseelTutorialUnderstandingSEM2025_Interactive_03.qmd 
            text: "ℹ Tutorial von Rosseel & Vidal (2025) - 3" 
      - section: "(Beispiel-Code)"
        contents:
          - section: "Messmodelle (Thema 1-3)"
            contents:            
              - href: S06_Thema_01.qmd 
                text: "A | Thema 1" 
              - href: S06_Thema_02.qmd 
                text: "B | Thema 2"
              - href: S06_Thema_03.qmd 
                text: "C | Thema 3"
          - section: "Gruppenvergleiche (Thema 4-6)"
            contents:            
              - href: S07_Thema_04.qmd 
                text: "A | Thema 4" 
              - href: S07_Thema_05.qmd 
                text: "B | Thema 5"
              - href: S07_Thema_06.qmd 
                text: "C | Thema 6"
          - section: "Strukturmodelle (Thema 7-8)"
            contents:            
              - href: S08_Thema_07.qmd 
                text: "A | Thema 7" 
              - href: S08_Thema_08.qmd 
                text: "B | Thema 8"
          - section: "Mehrere Messzeitpunkte (Thema 9-10)"
            contents:                
              - href: S09_Thema_09.qmd 
                text: "A | Thema 9"                            
              - href: S09_Thema_10.qmd 
                text: "B | Thema 10"
            
theme:
  light: 
    - flatly 
    - theme_flatly.scss
  dark: 
    - darkly 
    - theme_darkly.scss            