---
title: "Rückblick: Explorative Faktorenanalyse"
format: live-html
engine: knitr
---
  
{{< include _extensions/r-wasm/live/_knitr.qmd >}}


```{webr}
#| warning: false
#| echo: false

webr::install("quadprog",  repos = "https://kroehne.github.io/webr-quadprog-repo")
 
suppressPackageStartupMessages(library(mnormt))
suppressPackageStartupMessages(library(lavaan))
suppressPackageStartupMessages(library(lavaanPlot))
suppressPackageStartupMessages(library(DT))

assignInNamespace("lav_options_checkinterval", function(x, nm, num2int) {
    if (any(is.na(x))) return(TRUE)
    if (num2int) x <- as.integer(x)                                                                                              
    oks <- vapply(x, function(x1) {
      (x1 > nm$bounds[1] || (x1 == nm$bounds[1] && nm$first.in)) &&                                                              
      (x1 < nm$bounds[2] || (x1 == nm$bounds[2] && nm$last.in))                                                                  
    }, TRUE)
    all(oks)                                                                                                                     
  }, ns = "lavaan")

model_3f <-  "visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9"

fit_3f <- cfa(model_3f, data = HolzingerSwineford1939)

options(mc.cores = 1)

View <- function(dat){
  dat_name <- deparse(substitute(dat))
  df_display <- dat |>
  dplyr::mutate(
    dplyr::across(everything(), ~ ifelse(is.na(.x), "❌ (NA)", .x))
  )
  
  DT::datatable(
    df_display,
    rownames = FALSE, 
    options = list(
      pageLength = 5,
      scrollX = TRUE,
      dom = 'tip',   
      columnDefs = list(list(className = 'dt-center', targets = "_all"))
    ),
    caption = htmltools::tags$caption(
      style = 'caption-side: top; text-align: left;',
      'data.frame: ', htmltools::strong(dat_name)
    )
  )  
}
```

::: {.callout-important title="Rückblick"}
Interpretieren Sie die Ausgabe der folgenden *explorativen Faktorenanalyse*. Wie viele Faktoren werden benötigt, um die Struktur der $9$ Items zu erklären?
:::

<details>

<summary>Datensatzbeschreibung</summary>
Der Datensatz `HolzingerSwineford1939` ist ein klassischer Beispieldatensatz für konfirmatorische Faktorenanalyse und Strukturgleichungsmodelle. Er ist im R-Paket `lavaan` enthalten und basiert auf der Studie von Holzinger und Swineford (1939) zu mentalen Fähigkeitsleistungen von Schülerinnen und Schülern. Der in `lavaan` enthaltene Datensatz umfasst 301 Beobachtungen von Kindern der siebten und achten Klasse aus zwei Schulen, `Pasteur` und `Grant-White`. Die vollständige Originalstudie enthielt 26 Testvariablen; in der SEM-Literatur wird jedoch häufig eine Teilmenge von 9 Variablen verwendet.  

| Variable | Beschreibung | Übliche Faktorzuordnung |
|---|---|---|
| `x1` | Visual perception / visuelle Wahrnehmung | `visual` |
| `x2` | Cubes / Würfelaufgaben | `visual` |
| `x3` | Lozenges / Rauten- bzw. Formenaufgaben | `visual` |
| `x4` | Paragraph comprehension / Text- bzw. Absatzverständnis | `textual` |
| `x5` | Sentence completion / Satzergänzung | `textual` |
| `x6` | Word meaning / Wortbedeutung | `textual` |
| `x7` | Speeded addition / Additionsaufgaben unter Zeitdruck | `speed` |
| `x8` | Speeded counting of dots / Punkte zählen unter Zeitdruck | `speed` |
| `x9` | Speeded discrimination of straight and curved capitals / Unterscheidung gerader und gebogener Großbuchstaben unter Zeitdruck | `speed` |

</details>

```{webr}
#| warning: false
#| echo: true
#| autorun: true
library(lavaan)
var.names <- paste("x", 1:9, sep = "")
var.names
```

<details>
<summary>Itemdaten ansehen</summary>
```{webr}
#| warning: false
#| echo: true
#| autorun: false
View(HolzingerSwineford1939[,var.names])
```
</details>

```{webr}
#| warning: false
#| echo: true
#| autorun: true
fit <- efa(data = HolzingerSwineford1939[,var.names], 
           nfactors = 1:4)
summary(fit)
```

Scree-Plot

```{webr}
#| warning: false
#| echo: true
#| autorun: true
fit_4f <- fit[[4]]
cor_mat <- lavInspect(fit_4f, "cor.ov")
ev <- eigen(cor_mat)$values
plot(ev, type="b", main="Scree-Plot (HolzingerSwineford1939)", 
     xlab="Faktor", ylab="Eigenwert")


```

Parallel-Analyse^[Hier durchgeführt mit der Funktion `fa.parallel()` aus dem R-Paket `psych`. ]

```{webr}
#| warning: false
#| echo: true
#| autorun: true
library(psych)
data(HolzingerSwineford1939)
df <- HolzingerSwineford1939[, paste0("x", 1:9)]
invisible(capture.output({
  pa <- fa.parallel(
    df, 
    fm = "ml",         
    fa = "both",       
    n.iter = 100,       
    show.legend = TRUE,
    ylabel = "Eigenwert für PCA und FA",
    main = "Parallelanalyse (HolzingerSwineford1939)"
  )}))
```


<details>
<summary>SPOILER!</summary>

```{webr}
#| warning: false
#| echo: true
#| autorun: true

cat("Kaiser-Kriterium (Eigenwert > 1): 3 Faktoren\n\n")
cat("Scree-Plot (rechts vom Knick nur 'Geröll'): 2 oder 4 ?\n\n") 
cat("Parallel-Analyse (blaue Linie oberhalb der roten Linie): 3 Faktoren / 3 Komponenten \n\n")
```

</details>

---

Referenzen:

Holzinger, K. J., & Swineford, F. (1939). A study in factor analysis: The stability of a bi-factor solution. University of Chicago. https://books.google.de/books?id=io6cMQEACAAJ
